CREATE TABLE PhieuGiamGia (maPhieu varchar(10) NOT NULL, tieuDe varchar(500) NOT NULL, tieuDeNgan varchar(200) NOT NULL, diemNoiBat varchar(1000) NOT NULL, dieuKien varchar(1000) NOT NULL, noiDung varchar(1000) NOT NULL, thoiGianBatDau date NOT NULL, thoiGianKetThuc date NOT NULL, ngayHetHan date NOT NULL, soLuongNhoNhat int(10) NOT NULL, soLuongMotUser int(10) NOT NULL, soLuongDaMua int(10) NOT NULL, giaGoc float NOT NULL, giaBan float NOT NULL, hoaHong int(10) NOT NULL, tinhTrang tinyint(1) NOT NULL, sendAds tinyint(1) NOT NULL, DanhMucmadm int(10) NOT NULL, CongTymact int(10) NOT NULL, PRIMARY KEY (maPhieu));
CREATE TABLE DonDatHang (madh int(10) NOT NULL AUTO_INCREMENT, hoTen varchar(50) NOT NULL, diaChi varchar(200) NOT NULL, dienThoai varchar(50) NOT NULL, soLuong int(10) NOT NULL, loiNhan varchar(255), ngayMua date, ngayXacNhan date, ngayGiao date, ngayHoanTat date, ngayHuy date, tinhTrang int(10) NOT NULL, huy tinyint(1) NOT NULL, NguoiDungemail varchar(50) NOT NULL, PhieuGiamGiamaPhieu varchar(10) NOT NULL, PRIMARY KEY (madh));
CREATE TABLE NguoiDung (email varchar(50) NOT NULL, username varchar(20) NOT NULL, password varchar(50) NOT NULL, quyenAdmin tinyint(1) NOT NULL, hoTen varchar(50), cmnd varchar(50), dienThoai varchar(50), diaChi varchar(200), gioiTinh tinyint(1) NOT NULL, ngaySinh date, nguyenQuan varchar(50), activeCode varchar(50), tinhtrang tinyint(1) NOT NULL, DonDatHangmadh int(10) NOT NULL, PRIMARY KEY (email));
CREATE TABLE CongTy (mact int(10) NOT NULL AUTO_INCREMENT, tenct varchar(100) NOT NULL, diaChi varchar(100) NOT NULL, email varchar(50), nguoiDaiDien varchar(50), websiteUrl varchar(50), dienThoai varchar(50) NOT NULL, fax varchar(50), tinhTrang tinyint(1) NOT NULL, PRIMARY KEY (mact));
CREATE TABLE DanhMuc (madm int(10) NOT NULL AUTO_INCREMENT, tendm varchar(50) NOT NULL, tinhTrang tinyint(1) NOT NULL, PRIMARY KEY (madm));
CREATE TABLE KhuVuc (makv int(10) NOT NULL AUTO_INCREMENT, tenkv varchar(50) NOT NULL, tinhTrang tinyint(1) NOT NULL, PRIMARY KEY (makv));
CREATE TABLE KhuVuc_PGG (tinhTrang tinyint(1) NOT NULL, PhieuGiamGiamaPhieu varchar(10) NOT NULL, KhuVucmakv int(10) NOT NULL);
CREATE TABLE ThaoLuan (matl int(10) NOT NULL AUTO_INCREMENT, email varchar(50) NOT NULL, noiDung varchar(200) NOT NULL, tinhTrang tinyint(1) NOT NULL, PhieuGiamGiamaPhieu varchar(10) NOT NULL, PRIMARY KEY (matl));
CREATE TABLE HinhAnh (duongDan varchar(50) NOT NULL, anhNen tinyint(1) NOT NULL, tinhtrang tinyint(1) NOT NULL, PhieuGiamGiamaPhieu varchar(10) NOT NULL);
CREATE TABLE QuangCao (email varchar(100) NOT NULL, makv int(10) NOT NULL, tinhtrang tinyint(1) NOT NULL, PRIMARY KEY (email, makv));
CREATE VIEW `Browse Photo View` AS SELECT FROM;
ALTER TABLE PhieuGiamGia ADD CONSTRAINT FKPhieuGiamG292333 FOREIGN KEY (DanhMucmadm) REFERENCES DanhMuc (madm);
ALTER TABLE PhieuGiamGia ADD CONSTRAINT FKPhieuGiamG383585 FOREIGN KEY (CongTymact) REFERENCES CongTy (mact);
ALTER TABLE DonDatHang ADD CONSTRAINT FKDonDatHang537026 FOREIGN KEY (NguoiDungemail) REFERENCES NguoiDung (email);
ALTER TABLE DonDatHang ADD CONSTRAINT FKDonDatHang5991 FOREIGN KEY (PhieuGiamGiamaPhieu) REFERENCES PhieuGiamGia (maPhieu);
ALTER TABLE KhuVuc_PGG ADD CONSTRAINT FKKhuVuc_PGG793822 FOREIGN KEY (PhieuGiamGiamaPhieu) REFERENCES PhieuGiamGia (maPhieu);
ALTER TABLE KhuVuc_PGG ADD CONSTRAINT FKKhuVuc_PGG421149 FOREIGN KEY (KhuVucmakv) REFERENCES KhuVuc (makv);
ALTER TABLE HinhAnh ADD CONSTRAINT FKHinhAnh858750 FOREIGN KEY (PhieuGiamGiamaPhieu) REFERENCES PhieuGiamGia (maPhieu);
ALTER TABLE ThaoLuan ADD CONSTRAINT FKThaoLuan489760 FOREIGN KEY (PhieuGiamGiamaPhieu) REFERENCES PhieuGiamGia (maPhieu);
